/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as YonetimRouteImport } from './routes/yonetim'
import { Route as OgretmenIndexRouteImport } from './routes/ogretmen/index'
import { Route as OgretmenTeacherIdRouteImport } from './routes/ogretmen/$teacherId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const YonetimRoute = YonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => rootRouteImport,
} as any)
const OgretmenIndexRoute = OgretmenIndexRouteImport.update({
  id: '/ogretmen/',
  path: '/ogretmen/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgretmenTeacherIdRoute = OgretmenTeacherIdRouteImport.update({
  id: '/ogretmen/$teacherId',
  path: '/ogretmen/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/yonetim': typeof YonetimRoute
  '/ogretmen/$teacherId': typeof OgretmenTeacherIdRoute
  '/ogretmen/': typeof OgretmenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/yonetim': typeof YonetimRoute
  '/ogretmen/$teacherId': typeof OgretmenTeacherIdRoute
  '/ogretmen': typeof OgretmenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/yonetim': typeof YonetimRoute
  '/ogretmen/$teacherId': typeof OgretmenTeacherIdRoute
  '/ogretmen/': typeof OgretmenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai' | '/yonetim' | '/ogretmen/$teacherId' | '/ogretmen/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai' | '/yonetim' | '/ogretmen/$teacherId' | '/ogretmen'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/yonetim'
    | '/ogretmen/$teacherId'
    | '/ogretmen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  YonetimRoute: typeof YonetimRoute
  OgretmenTeacherIdRoute: typeof OgretmenTeacherIdRoute
  OgretmenIndexRoute: typeof OgretmenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yonetim': {
      id: '/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof YonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogretmen/': {
      id: '/ogretmen/'
      path: '/ogretmen'
      fullPath: '/ogretmen/'
      preLoaderRoute: typeof OgretmenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogretmen/$teacherId': {
      id: '/ogretmen/$teacherId'
      path: '/ogretmen/$teacherId'
      fullPath: '/ogretmen/$teacherId'
      preLoaderRoute: typeof OgretmenTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  YonetimRoute: YonetimRoute,
  OgretmenTeacherIdRoute: OgretmenTeacherIdRoute,
  OgretmenIndexRoute: OgretmenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
